### ISSUE TITLE
Not being able to visualize it in Colab

### ISSUE THREAD

**Issue by diogoalvesderesende** [Rambatino/CHAID#116] opened 2021-02-13 09:23 UTC
Hey,

Thanks for the library, it is fantastic to have a python version of CHAID!

I am having issues visualizing the tree model. I get some error about orca and I cannot find a way to solve. Would you have any idea on how to fix it? 

Please find here the link to the script:
https://colab.research.google.com/drive/1pteueOMAd_QhioL5Kw9FyfqmhaMpHoYi?usp=sharing

Thanks,
Diogo

**Comment by Rambatino** [comment] 2021-02-15 10:08
Hey thanks for your interest and for the issue you've found! 

I have seen that error before.

Have you set up both the graphviz and orca as in here:

graphviz: https://stackoverflow.com/questions/35064304/runtimeerror-make-sure-the-graphviz-executables-are-on-your-systems-path-aft
orca: https://github.com/plotly/orca

**Comment by soonmi-m** [comment] 2021-02-15 15:37
I have a similar problem.

For the graphviz, I followed this video to got it to work.
https://www.youtube.com/watch?v=kOYnlqbZ8K4
For orca, I was able to install it and verify that the orca executable is available on my path through command prompt.

However, even with those addressed, I am still unable to get the visual to work. 

I'm still pretty new to Python, so I was going to ask if I'm supposed to put something specific in path = ? I tried putting the path to the folder where my data and .ipynb file is and it didn't work. I also tried putting the path to where my orca file is, but it didn't work. 

This is what I get as my error:

**tree.to_tree()**
<treelib.tree.Tree at 0x1fd4f262d90>

**tree.render(path= None, view=False)**
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-83-a4fad81aec17> in <module>
----> 1 tree.render(path= None, view=False)

~\anaconda3\lib\site-packages\CHAID\tree.py in render(self, path, view)
    289 
    290     def render(self, path=None, view=False):
--> 291         Graph(self).render(path, view)

~\anaconda3\lib\site-packages\CHAID\graph.py in render(self, path, view)
     75                     edge_label = "     ({})     \n ".format(', '.join(map(str, node.choices)))
     76                     g.edge(str(node.parent), str(node.node_id), xlabel=edge_label)
---> 77             g.render(path, view=view)
     78 
     79     def bar_chart(self, node):

~\anaconda3\lib\site-packages\graphviz\files.py in render(self, filename, directory, view, cleanup, format, renderer, formatter, quiet, quiet_view)
    236         relative to the DOT source file.
    237         """
--> 238         filepath = self.save(filename, directory)
    239 
    240         if format is None:

~\anaconda3\lib\site-packages\graphviz\files.py in save(self, filename, directory)
    198 
    199         log.debug('write %d bytes to %r', len(data), filepath)
--> 200         with io.open(filepath, 'w', encoding=self.encoding) as fd:
    201             fd.write(data)
    202             if not data.endswith(u'\n'):

OSError: [Errno 22] Invalid argument: 'trees\\2021-02-15 10:30:54.gv'

**Comment by Rambatino** [comment] 2021-02-15 16:16
So the glaring issue in the colab notebook is: 

``` python
plotly.io.orca.config.executable = '/path/to/orca'
```

As /path/to/orca is the example rather than the actual path to orca.

I've recreated it locally, will see if fixing the path works.

**Comment by soonmi-m** [comment] 2021-02-15 16:33
This might be a silly misunderstanding on my end, but I tried getting the path through the desktop orca properties and through my anaconda folder, and still got errors (even if I take out the quotes, it doesn't work). 

![image](https://user-images.githubusercontent.com/74330470/107972204-7fc4cb80-6f81-11eb-86ad-f851413ba12f.png)

**Comment by Rambatino** [comment] 2021-02-15 17:56
So it's not the program I don't think. It's the executable.

For my mac I installed orca using `brew install orca`. I then ran orca and it moved the cli into my /usr/local/bin:

Therefore:
``` bash
➜  ~ which orca
/usr/local/bin/orca
```



![image](https://user-images.githubusercontent.com/3631109/107979824-25466200-6fb7-11eb-8420-91d29709dda8.png)

**Comment by Rambatino** [comment] 2021-02-15 17:57
(I recreated the issue, then installed orca. When I opened the program it then moved the cli into /usr/local/bin)

**Comment by Rambatino** [comment] 2021-02-15 17:58
Because it was in a standard path you don't need to specify the location of orca.

**Comment by Rambatino** [comment] 2021-02-15 17:59
`which orca` needs to return a path for unix systems (including mac). `where orca` needs to return the correct path for windows systems 

https://www.shellhacks.com/windows-which-equivalent-cmd-powershell/#:~:text=The%20where%20command%20is%20a,of%20executable%20commands%20in%20Windows.

**Comment by Rambatino** [comment] 2021-02-15 18:00
> This might be a silly misunderstanding on my end, but I tried getting the path through the desktop orca properties and through my anaconda folder, and still got errors (even if I take out the quotes, it doesn't work).
> 
> ![image](https://user-images.githubusercontent.com/74330470/107972204-7fc4cb80-6f81-11eb-86ad-f851413ba12f.png)

I'm not exactly sure what the issue is there. Have you tried double quotes rather than single?

**Comment by soonmi-m** [comment] 2021-02-15 18:38
> > This might be a silly misunderstanding on my end, but I tried getting the path through the desktop orca properties and through my anaconda folder, and still got errors (even if I take out the quotes, it doesn't work).
> > ![image](https://user-images.githubusercontent.com/74330470/107972204-7fc4cb80-6f81-11eb-86ad-f851413ba12f.png)
> 
> I'm not exactly sure what the issue is there. Have you tried double quotes rather than single?

I have :/

**Comment by xulaus** [comment] 2021-02-15 18:48
the Unicodeescape error is because python is interpreting `\U` as the start of a unicode literal. You need double backslashes to escape a backslash properly, or I think forward slashes work for paths most of the time on windows systems.
```
In [1]: print("C:\Users")                                                                                                                                                                                                                                                                               
  File "<ipython-input-16-83edfbd11c98>", line 1
    print("C:\Users")
          ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape


In [2]: print("C:\\Users")                                                                                                                                                                                                                                                                              
C:\Users
```

**Comment by soonmi-m** [comment] 2021-02-15 19:51
I got the path to work, but now I'm back to the initial problem I had with the invalid argument in trees. -_-
I tried to specify my path to somewhere on my computer, then ran into an access problem, which might not be worth investigating since I am just an intern...

Thank you for your responses! The CHAID package works really well for me otherwise and has been helpful.

![image](https://user-images.githubusercontent.com/74330470/107987711-844aad80-6f9c-11eb-8241-34556a2ee03d.png)

**Comment by Rambatino** [comment] 2021-02-16 09:05
@soonmi-m this seems to be a different problem to the orca issue above.

@diogoalvesderesende let's carry on the orca issue here. The difficult thing is that you need to get it to install in colab, and also you need to make the visual in-line. I don't think it's a trivial problem, unfortunately.

**Comment by diogoalvesderesende** [comment] 2021-02-16 10:31
Hey Mark, 

Hey Mark,
I have managed. Not able to plot in-line, but I take what I get. Thanks for the help! For Google Colab, you need to install this as well:
```
!pip install plotly>=4.0.0
!wget https://github.com/plotly/orca/releases/download/v1.2.1/orca-1.2.1-x86_64.AppImage -O /usr/local/bin/orca
!chmod +x /usr/local/bin/orca
!apt-get install xvfb libgtk2.0-0 libgconf-2-4
```

Then for the visualization, this worked for me:
```
#Visualization
import orca
import plotly
import plotly.graph_objects as go
tree.render(path=None, view=True)
```

Again, great package. I have a few questions that hopefully you could help me to take it the next level:

1) If I factorize the predictors, would it also work?
2) Is there a way to customize the plot? I.e., increase font size.

I believe CHAID is one of the most underrated techniques out there. Thank you for your work!!

Best,
Diogo

**Comment by Rambatino** [comment] 2021-02-18 13:22
> 2. Is there a way to customize the plot? I.e., increase font size.
Not currently, no. I haven't really put much thought into the plot. If you want to do a PR with increased font size (and any other cosmetic changes) I'll approve, merge and release.

> 1. If I factorize the predictors, would it also work?
Maybe, I'm not quite sure what you mean

**Comment by diogoalvesderesende** [comment] 2021-02-18 18:52
Hey Mark,

I mean if I were to use OneHotEncoder, or the factorize function from
Pandas, would it also work? Currently, the examples are only with binary
variables.

I would love to do a PR, but my Python, and knowledge of it is not good
enough :/

Thanks and best,
Diogo

**Comment by Rambatino** [comment] 2021-02-19 09:50
The ChiSquare stats functions permits any number of categorical variables (it doesn't need to be binary), but the results are more difficult to interpret (and also the likelihood for sub combinations to be significant increases) - One hot encoding is really useful for giving easier to explain answers because everything is equally weighted as a yes/no binary variable (see my answer here for an easy way to do it in pandas: https://stackoverflow.com/a/52507931/1744107)

If you were to run your notebook locally, then you can edit the config here:

https://github.com/Rambatino/CHAID/blob/master/CHAID/graph.py#L28

And you can play around with these variables and it _should_ change the output in the tree.

To make your changes available you'll need to pip install like here (and restart the notebook python kernel between changes):

![image](https://user-images.githubusercontent.com/3631109/108487988-c115ed80-7297-11eb-8717-bb08bf712eea.png)


If it looks better I'll 💯 approve and merge the PR

**Comment by Rambatino** [comment] 2021-02-23 20:28
closing PR as seems resolved

**Closed by Rambatino** 2021-02-23 20:28 UTC
